# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='code',
            field=models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=models.TextField(default='', help_text='类别描述', verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='goods.GoodsCategory', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='desc',
            field=models.TextField(default='', help_text='品牌描述', max_length=200, verbose_name='品牌描述'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/'),
        ),
        migrations.AlterModelTable(
            name='goodscategorybrand',
            table='goods_goodsbrand',
        ),
    ]
